name: Python Build and Deploy
on:
  workflow_dispatch:
    inputs:
      run_test: 
        description: 'Run tests during the build'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
    
jobs:
  build-deploy: 
    runs-on: ubuntu-latest
    env:
      PYTHON_ENV: python3
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3'
    - name: Create & Activate Virtual Environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests (Conditional)
      if: inputs.run_test == 'true'
      run: |
        pytest --maxfail=5 --disable-warnings -q

    - name: Build Package
      run: |
        python -m build

    - name: Deploy to Test PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: | 
        pip install --upgrade twine 
        twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
    - name: Cleanup
      if: always()
      run: |
        rm -rf venv

    - name: Notify on Success
      if: success()
      run: echo "Build completed successfully!"
    - name: Notify on Failure
      if: failure()
      run: echo "Build failed!"
